name: Get system diffs on PR
on:
  check_suite:
    types: [completed]

jobs:
  get-diff:
    runs-on: ubuntu-latest
    if: github.event.check_suite.app.name == 'Garnix CI'
        && github.event.check_suite.conclusion == 'success'
        && github.event.check_suite.latest_check_runs_count >= 4
        && github.event.check_suite.head_branch == 'update_flake_lock_action'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build current system
        run: |
          set -eux
          nix run github:mic92/nix-fast-build -- \
            --no-nom \
            --flake .#patroclus \
            --out-link old
      - name: Build new system
        run: |
          set -eux
          git checkout update_flake_lock_action
          git rebase main
          nix run github:mic92/nix-fast-build -- \
            --no-nom \
            --flake .#patroclus \
            --out-link new
      - name: Get diff
        run: |
          nix run gitlab:khumba/nvd --no-write-lock-file -- \
            diff old new
